# Generated by Django 3.2.4 on 2021-06-13 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_auto_20210608_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='descr',
            field=models.TextField(verbose_name='وصف'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main_app.Tag', verbose_name='وسوم'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(verbose_name='رابط'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='task',
            name='descr',
            field=models.TextField(verbose_name='وصف'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(verbose_name='أولوية'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main_app.Tag', verbose_name='وسوم'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
