# Generated by Django 3.2.4 on 2021-06-14 19:49

from django.db import migrations
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210614_2159'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='bookmark',
        #     name='tags',
        #     field=main_app.models.TagsRelation(blank=True, to='main_app.Tag', verbose_name='وسوم'),
        # ),
    ]
