# Generated by Django 3.2.4 on 2021-06-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_bookmark_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main_app.Tag', verbose_name='وسوم'),
        ),
    ]
