# Generated by Django 3.2.4 on 2021-06-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_bookmark_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='تم التنبيه'),
        ),
    ]
